# Generated by Django 2.1.2 on 2018-10-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cdalterdata',
            field=models.IntegerField(default=1, verbose_name='Cód. Alterdata'),
            preserve_default=False,
        ),
    ]
